### ISSUE TITLE
Make some Themed buttons enabled or disabled 

### ISSUE THREAD

**Issue by tiberiupvisan** [Bryanx/themed-toggle-button-group#12]
First of all, thank you for this library. It's pretty useful 👍 

Although, I found a need to have some buttons enabled/disabled. Since the `clickEvent` is handled in the group class, I had some issues blocking it. I guess a simple solution is to check in the `addClickListeners` method if the button is enabled or not.

My workaround looks something like this and it works fine: 
```kotlin 
@SuppressLint("ClickableViewAccessibility")
    private fun addClickListeners(btn: ThemedButton) {
        btn.cvCard.setOnTouchListener { _, event ->
            if (btn.isEnabled) {
                selectButtonWithAnimation(btn, event.x, event.y)
                if (event.action == MotionEvent.ACTION_UP) btn.performClick()
                event.action == MotionEvent.ACTION_UP
            } else false
        }
    }
```

**Comment by Bryanx** [comment]
Hey, thanks for mentioning your solution. I implemented something similar [here](https://github.com/Bryanx/byheart/blob/master/app/src/main/java/nl/bryanderidder/byheart/rehearsal/setup/RehearsalSetupFragment.kt#L116). In my case I showed a warning message instead of disabling the button entirely. I guess this solution is fine for now. If more people request an enable/disable feature we can add it to the library.

**Comment by Bryanx** [comment]
I have added this to the next version (1.4.0)
